#ifndef __JOBSEPARATOR_H__
#define __JOBSEPARATOR_H__

#define PGPRC_PERPAGE_TOTALPHOTOS_PAGE_1 	 (PGPRC_CONTACTIMAGE_NUMACCROSS * PGPRC_CONTACTIMAGE_NUMDOWN_PAGE_1)
#define PGPRC_PERPAGE_TOTALPHOTOS_PAGE_N   (PGPRC_CONTACTIMAGE_NUMACCROSS * PGPRC_CONTACTIMAGE_NUMDOWN_PAGE_N)

#endif