//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by zeus.rc
//
#define IDC_INSTALL                     3
#define IDC_LOAD                        3
#define ID_HOLD                         3
#define IDC_DELETE                      4
#define IDC_CONNECT                     5
#define IDC_DELETE2                     5
#define IDC_ADD                         5
#define IDC_SHARE                       5
#define IDC_CONTROL_PANEL               5
#define IDC_CLONE                       6
#define IDS_RP95_BUILDVER               69
#define IDR_MAINFRAME                   70
#define IDR_MAINFRAME_640               71
#define IDS_RP95_BUILDVER_DEMO          71
#define IDR_PHZMAINFRAME                71
#define IDR_ZEUSTYPE                    72
#define IDC_RESET_STATUS                73
#define IDR_MAINFRAME_OLD               73
#define IDS_RLC_VER                     73
#define IDC_EDIT                        74
#define ID_REGEN                        75
#define ID_REPAINT                      76
#define IDS_ERR_NOLOAD_ODLL             77
#define IDC_NEW                         78
#define IDI_ICON_PREVIEW                80
#define IDS_RIPSECTION                  81
#define IDC_MEDIA_SOURCE_PRMPT          82
#define IDC_STOP                        83
#define IDS_MULTITASKING                84
#define IDS_PREVIEW                     85
#define IDS_PREVIEW_SIZE                86
#define IDS_PREVIEW_NUM                 87
#define IDC_PORTRAIT                    88
#define IDS_NOT_AVAIL                   89
#define IDC_LANDSCAPE                   90
#define IDS_QUEUESECTION                91
#define IDS_INITIALDIR                  92
#define IDS_MULTIPLE_SELECTION          93
#define IDS_DEV_DEFAULT                 94
#define IDS_DEV_ORIENTATION             95
#define IDS_DEV_COPIES                  96
#define IDC_ORIENTATION                 97
#define IDS_MAXDEVICES                  97
#define IDS_UNITS                       98
#define IDS_CHANGING_NAME               99
#define IDD_ABOUTBOX                    100
#define IDS_SERIALNUMBER                100
#define IDD_ZEUS_FORM                   101
#define IDS_RIPPROCAPP_DEBUG_NT         101
#define IDD_ZEUS_FORM_640               102
#define IDS_PREVIEWDLL_DEBUG_NT         102
#define IDC_MEDIA_SOURCE                103
#define IDS_BUILDING_SCANLINE           103
#define IDC_MEDIA_SIZE                  104
#define IDS_READING_FILE_COMPLETE       104
#define IDI_ICON1                       105
#define IDC_RESOLUTION                  105
#define IDS_ROTATING_BITMAP             105
#define IDI_ICON_FILEINFO_OLD           106
#define IDC_CONNECTION                  106
#define IDD_DIALOG_GPREFS_MAIN          107
#define IDC_ORIENTATION_LIST            107
#define IDD_FONT_MANAGER_PAGE           107
#define IDD_DEVSETUP                    108
#define IDD_DIALOG_GPREFS_DEVICE        109
#define CG_IDD_QUEUESTATUS              110
#define IDS_PROPSHT_CAPTION             112
#define IDD_DIALOG_GPREFS_RIP           113
#define IDD_JOBDEVPROPERTIES            115
#define IDD_JOBCLRPROPERTIES            116
#define IDD_DIALOG_GPREFS_EXTENSION     117
#define IDD_DIALOG_GPREFS_PREVIEW       123
#define IDD_DIALOG_GPREFS               123
#define IDB_BITMAP1                     125
#define IDD_DIALOG_PREFS_MAIN           126
#define IDD_DIALOG_PREFS_GENERAL        127
#define IDD_DIALOG_PREFS_NOTES          128
#define IDR_TOOLBAR_MAIN_SMALL          128
#define IDD_DIALOG_PREFS_COLOR          129
#define IDD_CUSTOM_FILE_DIALOG          130
#define IDD_DIALOG_PREVIEW              137
#define IDD_CLR_ADJUST_DIALOG           140
#define IDD_CMM_DIALOG                  141
#define IDD_DIALOG_PREFS_IMAGE          144
#define IDD_TRANSFORM                   147
#define IDI_LANDSCAPE                   149
#define IDI_PORTRAIT                    150
#define IDB_SPLASHWND                   151
#define IDD_SPLASH                      154
#define IDD_ZEUS_FORM_1024              155
#define IDB_SPLASHWND2                  157
#define IDI_ICON2                       160
#define IDC_DRAG                        165
#define IDI_ARROW                       166
#define IDD_PRINTDEV_FORM               192
#define IDR_ZEUSTYPE_NEW                194
#define IDR_ZEUSTYPE_OLD                195
#define IDB_STATUS_CHECK                220
#define IDB_STATUS_OK                   220
#define IDB_STATUS_HOLD                 226
#define IDB_STATUS_WAIT1                231
#define IDB_STATUS_WAIT3                232
#define IDB_STATUS_WAIT2                233
#define IDB_STATUS_NOTOK                236
#define IDD_ZEUS_FORM_OLD               274
#define IDI_ICON_FILEINFO2              275
#define IDI_ICON_FILEINFO               277
#define IDB_ITEM_SELECTED               278
#define IDB_ITEM_NOTSELECTED            279
#define IDR_MAINFRAME2                  296
#define IDR_MAINFRAME_1024              297
#define IDI_ICON3                       303
#define IDD_VISUAL_XFORM                318
#define IDD_ZEUS_FORM_NEW               319
#define IDD_VISUAL_XFORM2               319
#define IDD_DIALOG_GPREFS_RIP2          319
#define IDR_MAINFRAME_NEW               320
#define IDD_NEW_DEV_DIALOG              326
#define IDD_DEVICE                      326
#define IDB_BITMAP8                     329
#define IDB_LOCALPREFS                  330
#define IDB_LOCAL_PREFS                 330
#define IDB_GLOBAL_PREFS                331
#define IDB_BITMAP10                    337
#define IDB_PREFS_DTM                   337
#define IDB_PREFS_T                     339
#define IDB_PREFS_D                     340
#define IDB_PREFS_M                     341
#define IDB_PREFS_DT                    342
#define IDB_PREFS_DM                    343
#define IDB_PREFS_TM                    344
#define IDB_PREFS_NONE                  345
#define IDD_DIALOG_NEWXFORM             346
#define IDD_DIALOG_BHEADER              358
#define IDD_DIALOG_WINSPLIT             359
#define IDD_SERVERVIEW                  363
#define IDI_TEST                        366
#define IDD_VISUAL_CRAP                 369
#define IDD_DIALOG1                     371
#define IDD_LISTTEST                    374
#define IDB_BITMAP2                     375
#define IDI_CABICON                     376
#define IDD_CABINSTALL                  379
#define IDB_BITMAP3                     380
#define IDI_ICON4                       383
#define IDD_MODELESS_WAIT               385
#define IDD_DEVCONNECT                  386
#define IDB_BITMAP4                     387
#define IDI_ICON5                       388
#define IDR_POPUP                       392
#define IDD_DIALOG2                     394
#define IDD_LOADTRANSFORM               395
#define IDD_CLONE                       396
#define IDD_SAVE_XFORM                  399
#define IDD_SHARING                     400
#define IDI_PSOUT                       403
#define IDD_RIPSTATUS                   404
#define IDI_STATUS_OK                   406
#define IDI_STATUS_HOLD                 407
#define IDR_TOOLBAR_MAIN                408
#define IDR_TOOLBAR_PHZMAIN             409
#define IDR_TOOLBAR_PHZMAIN_SMALL       410
#define IDI_STATUS_WAIT1                411
#define IDI_STATUS_NOTOK                412
#define IDI_STATUS_PROPS_DEVICE         414
#define IDI_STATUS_PROPS_TRANSFORM      415
#define IDI_STATUS_PROPS_COLOR          416
#define IDI_STATUS_OK_DELETED           417
#define IDI_VISUALXFORM_ICON            418
#define IDD_IMAGE_PAUSE                 428
#define IDB_SPLASHWND_16                434
#define IDD_SCSI_EXPLORER               435
#define IDC_HAND                        436
#define IDD_PRINTER_NAMECHANGE          437
#define IDD_DEMO_DIALOG                 442
#define IDB_SPLASHWND_NEW               444
#define IDB_SPLASHWND_256_NEW           445
#define IDD_PREV_CTRL                   446
#define IDB_PREVCTRL_NEXT               447
#define IDB_PREVCTRL_PREV               448
#define IDB_PREVCTRL_BEGIN              449
#define IDB_PREVCTRL_END                450
#define IDD_JOBPROPERTIES               451
#define IDB_COLDTOOLBAR                 455
#define IDB_HOTTOOLBAR                  456
#define IDR_MFCAVI                      457
#define IDD_NEWQUEUE                    460
#define IDD_JOBSIZEPROPERTIES           461
#define IDD_QUEUEMEMORY                 465
#define IDD_WEBUPDATE                   467
#define IDB_RPICON                      470
#define IDI_OUR_HAND                    472
#define IDI_CROP                        473
#define IDD_JOBDESCRIPTION              474
#define IDD_NEWQUEUE2                   475
#define IDB_EDITPAGE                    476
#define IDD_SCAN_DIALOG                 477
#define IDD_CUSTOM_PAGE                 478
#define IDB_SPLASHWND_NEW_FUJI          480
#define IDB_SPLASHWND_256_NEW_FUJI      481
#define IDD_CMM_OLD_DIALOG              483
#define IDB_PREVCTRL_PRINT              484
#define IDB_PREVCTRL_CLOSE              485
#define IDI_PRINTTRAY                   487
#define IDI_PRINTTRAY1                  488
#define IDI_PRINTTRAY2                  489
#define IDI_PRINTTRAY3                  490
#define IDI_PRINTTRAY4                  491
#define IDB_PREVCTRL_ZOOMIN             491
#define IDB_PREVCTRL_ZOOMOUT            492
#define IDR_ZEUSPHZTYPE                 492
#define IDD_PRINT_INDEX                 493
#define IDD_DIALOG_GPREFS_PRINTINDEX    494
#define IDD_LICENSE_MANAGER             517
#define IDD_DOWNLOADFILE                518
#define IDD_SMA_EXPIRED                 519
#define IDB_HICOLOR_TOOLBAR             521
#define IDB_HICOLOR_TOOLBAR_DISABLED    522
#define IDB_HICOLOR_TOOLBAR_HOT         523
#define IDB_SPLASHWND_VERSION6          524
#define IDC_LIST1                       1000
#define IDC_XZOOM_EDIT                  1000
#define IDC_SCSI_LIST                   1000
#define ID_ADD_FONT                     1000
#define IDC_BROWSE_INPUT                1000
#define IDC_BROWSE_RGB                  1000
#define IDC_YZOOM_EDIT                  1001
#define IDC_BROWSE_PRESS                1001
#define ID_OK                           1002
#define IDC_XOFF_EDIT                   1002
#define IDC_INSTALLED_FONTS             1002
#define IDC_BROWSE_MONITOR              1002
#define ID_CANCEL                       1003
#define IDC_PRINTSEL                    1003
#define IDC_YOFF_EDIT                   1003
#define IDC_NEW_FONTS                   1003
#define IDC_BROWSE_PRINTER              1003
#define ID_ADDFILES                     1004
#define IDC_ROTATION_EDIT               1004
#define IDC_BROWSE_CMYK                 1004
#define IDC_FONTDIR_BROWSE              1004
#define IDC_DELETEFILES                 1005
#define IDC_XZOOM_SPIN                  1005
#define IDC_INFO                        1006
#define IDC_YZOOM_SPIN                  1006
#define IDC_FILENAME                    1007
#define IDC_SELECTALL                   1007
#define IDC_XOFF_SPIN                   1007
#define IDC_FONTDIR                     1007
#define IDC_PREVIEW_PANE                1007
#define IDC_FILESIZE                    1008
#define IDC_PREVIEWSEL                  1008
#define IDC_YOFF_SPIN                   1008
#define IDC_REMOVE_FONT                 1008
#define IDC_FULL_IMAGE_PANE             1008
#define IDC_FILEDATE                    1009
#define IDC_VXFORM                      1009
#define IDC_CANCEL                      1009
#define IDC_ROTATION_SPIN               1009
#define IDC_FILETIME                    1010
#define IDC_CONTINUE                    1010
#define ID_CLOSE                        1011
#define IDC_PAUSE                       1011
#define IDC_QUEUENAME                   1011
#define IDC_CLOSE                       1011
#define IDC_DESCRIPTION                 1012
#define IDC_BLANK                       1012
#define IDC_DESELECTALL                 1012
#define IDC_ALWAYSOPEN                  1012
#define IDC_ZOOMIN                      1012
#define IDC_BOUNDINGBOX                 1013
#define IDC_RESUME                      1013
#define IDC_AUTOADVANCE                 1013
#define IDC_ZOOMOUT                     1013
#define IDC_PREVIEWSTATUS               1014
#define IDC_HOSTID_EDIT                 1014
#define IDC_SHOWRULERS                  1014
#define IDC_STATUS                      1015
#define IDC_HOSTID_SPIN                 1015
#define IDC_FILETYPE                    1016
#define IDC_COPIES                      1017
#define IDC_PAGES                       1017
#define IDC_TRANSFORM                   1018
#define IDC_COPIES2                     1018
#define IDC_MEM_USED_EDIT               1018
#define IDC_DEVICE                      1019
#define IDC_PAGES2                      1019
#define IDC_DISKFILESMAX_EDIT           1019
#define IDC_LISTJOBS_EDIT               1020
#define IDC_HOTFOLDER_EDIT              1021
#define IDC_HOTFOLDER_DELAY             1021
#define IDC_HF_SELECTDPI                1022
#define IDC_HF_VARIANCE                 1023
#define IDC_EMAIL                       1027
#define IDC_RED_CYAN                    1028
#define IDC_EDIT1                       1029
#define IDC_EXT_POSTSCRIPT              1029
#define IDC_NOTES1                      1029
#define IDC_CLONENAME                   1029
#define IDC_NEW_XFORM                   1029
#define IDC_SHARENAME                   1029
#define IDC_ATMPATH                     1029
#define IDC_PSOUT                       1029
#define IDC_DELAY_EDIT                  1029
#define IDC_OLDNAME                     1029
#define IDC_NAME                        1029
#define IDC_SPOOL_EDIT                  1029
#define IDC_PRANGE_EDIT                 1029
#define IDC_LEFTLOGO_EDIT               1029
#define IDC_SCRATCH_EDIT                1030
#define IDC_EDIT2                       1030
#define IDC_PREVIEW_SMALL               1030
#define IDC_EXT_EPS                     1030
#define IDC_NEWNAME                     1030
#define IDC_NOTES2                      1030
#define IDC_COMMENT                     1030
#define IDC_TTPATH                      1030
#define IDC_GREEN_MAGENTA               1030
#define IDC_RIGHTLOGO_EDIT              1030
#define IDC_ACTIVATIONCODE              1030
#define IDC_EDIT3                       1031
#define IDC_PREVIEW_MEDIUM              1031
#define IDC_EXT_TARGA                   1031
#define IDC_PASSWORD                    1031
#define IDC_BLUE_YELLOW                 1031
#define IDC_HOTFOLDERDIR_EDIT           1031
#define IDC_EDIT4                       1032
#define IDC_PREVIEW_LARGE               1032
#define IDC_EXT_PCX                     1032
#define IDC_EDIT5                       1033
#define IDC_EXT_GIF                     1033
#define IDC_EDIT6                       1034
#define IDC_EXT_TIFF                    1034
#define IDC_PREVIEW_NUM                 1035
#define IDC_EXT_SCODL                   1035
#define IDC_COMBO1                      1036
#define IDC_OUTPUT_SIZE                 1036
#define IDC_IMAGE_REND_INTENT           1036
#define IDC_IMAGESIZE_UNITS             1036
#define IDC_COMBO2                      1037
#define IDC_TEXT_REND_INTENT            1037
#define IDC_WHITE_SPACE_UNITS           1037
#define IDC_NOTES                       1038
#define IDC_OPTIONS                     1040
#define IDC_NUMSELECTED                 1041
#define IDC_BUTTON3                     1042
#define IDC_RIP_TIME                    1042
#define IDC_APPLY                       1042
#define IDC_BROWSE                      1042
#define IDC_OURHELP                     1043
#define IDC_SPIN2                       1044
#define IDC_SELECT_POLLDIR              1044
#define IDC_PROPERTIES                  1044
#define IDC_ADVANCED                    1044
#define IDC_PANEL3D1                    1045
#define IDC_DEFAULTS                    1045
#define IDC_CONNECT2                    1045
#define IDC_POLL_DIR                    1046
#define IDC_RENAME                      1046
#define IDC_FRAME3D2                    1048
#define IDC_RIP_STATUS                  1049
#define IDC_RIP_STATUS2                 1050
#define IDC_TITLE_SELECTED              1051
#define IDC_TITLE_INDEX                 1052
#define IDC_TITLE_FILENAME              1053
#define IDC_TITLE_DESCRIPTION           1054
#define IDC_TITLE_STATUS                1055
#define IDC_TITLE_PREFS                 1056
#define IDC_TITLE_TIME                  1057
#define IDC_DUMMY1                      1057
#define IDC_DUMMY2                      1058
#define IDC_FREE_PHYSICAL               1059
#define IDC_FREE_VIRTUAL                1060
#define IDC_RARELY                      1061
#define IDC_SOMETIMES                   1062
#define IDC_OFTEN                       1063
#define IDC_BITMAP_FRAME                1065
#define IDC_MID                         1066
#define IDC_SITECODE                    1067
#define IDC_DAYSLEFT                    1068
#define IDC_WORKFORCESTATUS             1070
#define IDC_CDPRODUCERSTATUS            1071
#define IDC_ADDFILES                    1072
#define IDC_WIDTH_EDIT                  1072
#define IDC_RIPMEM_AUTO                 1073
#define IDC_WIDTH_SPIN                  1073
#define IDC_WIDTH_PRMPT                 1074
#define IDC_RIPMEM_EDIT                 1075
#define IDC_HEIGHT_EDIT                 1075
#define IDC_RIPMEM_SPIN                 1076
#define IDC_HEIGHT_PRMPT                1076
#define IDC_HEIGHT_SPIN                 1077
#define IDC_CYAN_EDIT                   1078
#define IDC_MAGENTA_EDIT                1079
#define IDC_RED_GAMMA                   1080
#define IDC_INPUTVALUE_EDIT             1080
#define IDC_GREEN_GAMMA                 1081
#define IDC_OUTPUTVALUE_EDIT            1081
#define IDC_BLUE_GAMMA                  1082
#define IDC_XOFFSET_PRMPT               1082
#define IDC_YELLOW_EDIT                 1083
#define IDC_BLACK_GAMMA                 1083
#define IDC_XOFFSET_EDIT                1083
#define IDC_XOFFSET_SPIN                1084
#define IDC_BRIGHTNESS_EDIT             1085
#define IDC_SPIN_COPIES                 1087
#define IDC_SPIN_CONTROL                1088
#define IDC_INPUT_PROFILE               1088
#define IDC_RGB_PROFILE                 1088
#define IDC_YOFFSET_PRMPT               1088
#define IDC_PREVIEW_EDIT                1089
#define IDC_MEM_USED_SPIN               1089
#define IDC_MAXPREVIEW_EDIT             1089
#define IDC_PRINTER_PROFILE             1089
#define IDC_YOFFSET_EDIT                1089
#define IDC_CANVAS                      1090
#define IDC_PRESS_PROFILE               1090
#define IDC_DISKFILESMAX_SPIN           1090
#define IDC_YOFFSET_SPIN                1090
#define IDC_MONITOR_PROFILE             1091
#define IDC_LISTJOBS_SPIN               1091
#define IDC_BRIGHTNESS                  1092
#define IDC_CMYK_PROFILE                1092
#define IDC_HOTFOLDER_SPIN              1092
#define IDC_HOTFOLDER_DELAY_SPIN        1092
#define IDC_CONTRAST                    1093
#define IDC_WHITE_IS_WHITE              1094
#define IDC_BLACK_IS_BLACK              1095
#define IDC_SNAP                        1100
#define IDC_RETAIN_ASPECT               1101
#define IDC_START_TYPE                  1102
#define IDC_TARGETFILE                  1103
#define IDC_TARGETDEVICE                1104
#define IDC_USERNAME                    1105
#define IDC_HATCH                       1105
#define IDC_ORGANIZATION                1106
#define IDC_SHOWPREVIEW                 1106
#define IDC_GLOBAL                      1107
#define IDC_SERIALNUMBER                1107
#define IDC_BASEDON                     1108
#define IDC_PREVIEW_CMM                 1108
#define IDC_MEDIA_SIZE_PRMPT            1109
#define IDC_PREPRESS                    1109
#define IDC_RIP_STATUS2_PANE            1110
#define IDC_RESOLUTION_PRMPT            1110
#define IDC_STATUS_TEXT                 1111
#define IDC_CONECTION_PRMPT             1111
#define IDC_ROTATION_PROMPT             1112
#define IDC_ORIENTATION_PRMPT           1112
#define IDC_PAGEDESC_PRMPT              1113
#define IDC_PAGEDIMS_PRMPT              1114
#define IDC_PRINTER_NAME                1116
#define IDC_XZOOM_PROMPT                1117
#define IDC_CORRECTION_TYPE             1117
#define IDC_YZOOM_PROMPT                1118
#define IDC_AREA_EDIT                   1118
#define IDC_XOFF_PROMPT                 1119
#define IDC_YOFF_PROMPT                 1120
#define IDC_AREA_PRMPT                  1120
#define IDC_IMAGECORNERS                1121
#define IDC_DATE                        1122
#define IDC_TIME                        1123
#define IDC_UNITS_PRMPT                 1123
#define IDC_SHOW_IMAGECOUNT             1124
#define IDC_IMAGECOUNT_EDIT             1125
#define IDC_IMAGECOUNT_SPIN             1126
#define IDC_IMAGECOUNT_TITLE            1127
#define IDC_BACKBLACK                   1128
#define IDC_BACKWHITE                   1129
#define IDC_BACKNONE                    1130
#define IDC_CURVE_FRAME                 1130
#define IDC_MAX_BLACK                   1131
#define IDC_MAX_INK                     1132
#define IDC_INSERT                      1133
#define IDC_GCR_UCR_SLIDER              1133
#define IDC_REMOVEFILE                  1134
#define IDC_COLORSPACE_LIST             1134
#define IDC_DELETEFILE                  1135
#define IDC_STATUS1                     1135
#define IDC_MONITOR_LABEL               1135
#define IDC_STATUS2                     1136
#define IDC_PRESS_LABEL                 1136
#define IDC_RESTORE                     1137
#define IDC_ELAPSED                     1137
#define IDC_STATUS_PERCENT              1137
#define IDC_COLOR_LIST                  1137
#define IDC_STATUS3                     1137
#define IDC_AVAILVERSION                1137
#define IDC_ELAPSED2                    1138
#define IDC_ADJUST_FRAME                1138
#define IDC_STATUS4                     1138
#define IDC_ADJUST_COLOR_LIST           1139
#define IDC_ICONIC                      1141
#define IDC_COMPRESSION                 1142
#define IDC_RED_GAMMA_LABEL             1142
#define IDC_GREEN_GAMMA_LABEL           1143
#define IDC_BLUE_GAMMA_LABEL            1144
#define IDC_GAMMA_LABEL                 1145
#define IDC_MAX_BLACK_LABEL             1146
#define IDC_BLUE_GAMMA_LABEL2           1147
#define IDC_BLACK_GAMMA_LABEL           1147
#define IDC_RED_CYAN_LABEL              1148
#define IDC_GREEN_MAGENTA_LABEL         1149
#define IDC_BLUE_YELLOW_LABEL           1150
#define IDC_RED_CYAN_LABEL2             1151
#define IDC_COLOR_TRANS_TYPE            1152
#define IDC_INPUTVALUE_LABEL            1152
#define IDC_LOCK_GRAPH                  1153
#define IDC_OUTPUTVALUE_LABEL           1153
#define IDC_SLIDER                      1154
#define IDC_LOCK_ADJUSTMENTS            1154
#define IDC_MAX_INK_LABEL               1155
#define IDC_GREEN_MAGENTA_LABEL2        1155
#define IDC_BLUE_YELLOW_LABEL2          1156
#define IDC_COLOR_LABEL                 1157
#define IDC_COLOR_SPACE_LABEL           1158
#define IDC_INPUT_LABEL                 1159
#define IDC_RGB_LABEL                   1159
#define IDC_MULTITASKING                1160
#define IDC_PRINTER_LABEL               1160
#define IDC_GENERIC1                    1161
#define IDC_GAMMASLIDE                  1161
#define IDC_LISTTEST                    1161
#define IDC_GCR_UCR_LABEL               1161
#define IDC_GENERIC2                    1162
#define IDC_BLACKSLIDE                  1162
#define IDC_ADJUST_FRAME_LABEL          1162
#define IDC_CMYK_LABEL                  1162
#define IDC_GENERIC3                    1163
#define IDC_CONTRASTSLIDE               1163
#define IDC_GCR_UCR_EDIT                1163
#define IDC_GENERIC4                    1164
#define IDC_CONTRAST_EDIT               1164
#define IDC_GENERIC5                    1165
#define IDC_CHECK1                      1166
#define IDC_INSTALLPRINTER              1166
#define IDC_PREVIEW                     1166
#define IDC_HOTFOLDER                   1166
#define IDC_LARGETOOLBAR                1166
#define IDC_IGNORE_ADJUSTMENTS          1166
#define IDC_ORIENTATION_OPTIMIZE        1166
#define IDC_SINGLEPAGE                  1166
#define IDC_AGFA_FILM                   1166
#define IDC_HELPDESK_CONTACT            1166
#define IDC_USE_EMBEDDED                1166
#define IDC_GAMMA_VAL                   1167
#define IDC_BRIGHTNESS_LABEL            1167
#define IDC_ENABLEPRINTSERVER           1167
#define IDC_AGFA_MINILABS               1167
#define IDC_HF_SELECTBYSIZE             1167
#define IDC_BLACK_VAL                   1168
#define IDC_CONTRAST_LABEL              1168
#define IDC_POLAROID_FILM               1168
#define IDC_CONTRAST_VAL                1169
#define IDC_GAMMA_LOW                   1170
#define IDC_GAMMA_HIGH                  1171
#define IDC_BLACK_HIGH                  1172
#define IDC_BLACK_LOW                   1173
#define IDC_CONTRAST_LOW                1174
#define IDC_CONTRAST_HIGH               1175
#define IDC_CHECK2                      1176
#define IDC_FINDDEVICE                  1176
#define IDC_CHECK3                      1177
#define IDC_COLOR_SELECT_LABEL          1177
#define IDC_PRANGE                      1177
#define IDC_WHITE_SPACE                 1177
#define IDC_COMPANY                     1177
#define IDC_BUTTON1                     1178
#define IDC_WEBSITE                     1178
#define IDC_NEXT                        1178
#define IDC_TRANSFORM_EDIT              1178
#define IDC_ADDFOLDER                   1178
#define IDC_SPOOL_BROWSE                1178
#define IDC_CHECKUPDATE                 1178
#define IDC_ADJ_DEFAULTS                1178
#define IDC_TRANSFORM_DEFAULTS          1178
#define IDC_SCSI_EXPLORER               1178
#define IDC_LEFTLOGO_LOAD               1178
#define IDC_GO                          1178
#define IDC_SCRATCH_BROWSE              1179
#define IDC_DEVLIST                     1179
#define IDC_DEVLIST_INSTALLED           1179
#define IDC_PREV                        1179
#define IDC_GETUPDATE                   1179
#define IDC_RIGHTLOGO_LOAD              1179
#define IDC_SERVER_ENABLE               1180
#define IDC_DEVLIST2                    1180
#define IDC_DEVLIST_AVAILABLE           1180
#define IDC_BEGIN                       1180
#define IDC_HOTFOLDERDIR_BROWSE         1180
#define IDC_SERVER_ONLYNEW              1181
#define IDC_END                         1181
#define IDC_SERVER_DELETE               1182
#define IDC_POLLNEW                     1185
#define IDC_POLLDIR                     1186
#define IDC_DETAILS                     1188
#define IDC_SKIPFILE                    1189
#define IDC_PROMPT1                     1190
#define IDC_PROMPT2                     1191
#define IDC_PATH                        1192
#define IDC_PROMPT                      1193
#define IDC_CONNECTLIST                 1194
#define IDC_SAVEAS                      1195
#define IDC_TLIST                       1196
#define IDC_RESET                       1196
#define IDC_LOCKPROPERTIES              1197
#define IDC_XFORM_LIST                  1200
#define IDC_XFORMLIST                   1202
#define IDC_NOTSHARED                   1203
#define IDC_SHARED                      1204
#define IDC_SHARENAME_TITLE             1205
#define IDC_COMMENT_TITLE               1206
#define IDC_PASSWORD_TITLE              1207
#define IDC_DEFAULT                     1208
#define IDC_BLENDS                      1210
#define IDC_IMAGEMEMORY                 1211
#define IDC_VIRTUALMEMORY               1212
#define IDC_BUFFERTODISK                1213
#define IDC_COMPRESS                    1214
#define IDC_AATYPE                      1215
#define IDC_INSTALLEDMEMORY             1216
#define IDC_AVAIL_PHYSICAL              1216
#define IDC_COMPRESS_BITMAP             1217
#define IDC_MEM_ALLOC                   1218
#define IDC_AAOVERSAMPLE                1219
#define IDC_DISKFILES_COMBO             1219
#define IDC_INSTALLED_MEM               1220
#define IDC_LISTJOBS_COMBO              1220
#define IDC_BITMAPSAMPLING              1220
#define IDC_POSTSCRIPT_OUTPUT           1221
#define IDC_HOTFOLDER_COMBO             1221
#define IDC_ONTOP                       1222
#define IDC_HOTFOLDER_INPANE            1222
#define IDC_PROGRESS                    1223
#define IDC_SELECTED                    1225
#define IDC_SERVER                      1226
#define IDC_ELAPSED_TIME                1227
#define IDC_DEVICE_PRMPT                1228
#define IDC_COPIES_PRMPT                1229
#define IDC_TRANSFORM_GRP               1230
#define IDC_DESCRIPTION_GRP             1231
#define IDOUROK                         1232
#define IDOURCANCEL                     1233
#define IDC_RIP_STATUS_PRMPT            1234
#define IDC_RIP_STATUS_PROGRESS         1235
#define IDC_DELAY_SPIN                  1236
#define IDC_TRANSFORM_PRMPT             1237
#define IDC_ENABLE_POLLING              1238
#define IDC_POLLING_DIR                 1239
#define IDC_POLLING_DIR_PRMPT           1240
#define IDC_DELAY_PRMPT                 1241
#define IDC_IMAGEONLY_NEW               1242
#define IDC_POLLING_GROUP               1243
#define IDC_STATUS_PRMPT                1245
#define IDC_PREVIEWSIZE                 1245
#define IDC_PREVIEWSIZE_PRMPT           1246
#define IDC_MAXPREVIEW_PRMPT            1247
#define IDC_MAXPREVIEW_SPIN             1248
#define IDC_TARGETFILE_PROMPT           1249
#define IDC_TARGETDEVICE_PROMPT         1250
#define IDC_START_TYPE_PROMPT           1251
#define IDC_NOTES_PROMPT                1252
#define IDC_FILENAME_PRMPT              1253
#define IDC_FILESIZE_PRMPT              1254
#define IDC_FILEDATE_PRMPT              1255
#define IDC_FILETIME_PRMPT              1256
#define IDC_DESCRIPTION_PRMPT           1257
#define IDC_FILETYPE_PRMPT              1258
#define IDC_PAGES_PRMPT                 1259
#define IDC_BOUNDINGBOX_PRMPT           1260
#define IDC_PREVIEWSTATUS_PRMPT         1261
#define IDC_IMAGEMEMORY_PRMPT           1262
#define IDC_AVAIL_PHYSICAL_PRMPT        1263
#define IDC_VIRTUALMEMORY_PRMPT         1264
#define IDC_MEM_ALLOC_PRMPT             1265
#define IDC_MEM_USED_PRMPT              1266
#define IDC_ADVANCED_RESOURCES          1267
#define IDC_MEMORY_BOX                  1267
#define IDC_ADVANCED_DATA_MANAGE        1268
#define IDC_ADVANCED_ANTIALIASING       1269
#define IDC_AATYPE_PRMPT                1270
#define IDC_AAOVERSAMPLE_PRMPT          1271
#define IDC_COMPRESS_PRMPT              1272
#define IDC_DELAY_PRMPT2                1273
#define IDC_ROTATION                    1274
#define IDC_SCALE_BITMAP                1275
#define IDC_UNITS                       1275
#define IDC_BACKGROUND                  1276
#define IDC_PREVIEW_SIZE                1276
#define IDC_BACKGROUND_PRMPT            1277
#define IDC_VERSION                     1278
#define IDC_PAGEDIMS                    1280
#define IDC_READ_TOTAL                  1281
#define IDC_PAGEDESC                    1281
#define IDC_COUNT                       1284
#define IDC_PRINT_STATUS_TEXT           1290
#define IDC_PRINT_STATUS_PROGRESS       1291
#define IDC_PREVIEW_STATUS_TEXT         1292
#define IDC_PREVIEW_STATUS_PROGRESS     1294
#define IDC_PRINT_STATUS_PROMPT         1295
#define IDC_PREVIEW_STATUS_PROMPT       1296
#define IDC_COPIES_EDIT                 1297
#define IDC_COPIES_SPIN                 1298
#define IDC_NAME_PRMPT                  1300
#define IDC_CONNECTION_PRMPT            1301
#define IDC_PREVIEW_PROGRESS            1302
#define IDC_CORR_TYPE                   1304
#define IDC_LISTJOBS_PRMPT              1305
#define IDC_DISKFILES_PRMPT             1306
#define IDC_HOTFOLDER_PRMPT             1307
#define IDC_INSERT_HOTFOLDER_PRMPT      1308
#define IDC_HOTFOLDER_INPANE_PRMPT      1308
#define IDC_COORDS_PROMPT               1311
#define IDC_PREVIEW_SIZE_PROMPT         1312
#define IDC_PREVIEW_SIZE_PRMPT          1312
#define IDC_UNITS_PROMPT                1313
#define IDC_CURRENTVERSION              1314
#define IDC_CURRENTVERSION_PRMPT        1315
#define IDC_AVAILVERSION_PRMPT          1316
#define IDC_LOGO                        1317
#define IDC_BLAH                        1318
#define IDC_DEVICE_BOX                  1319
#define IDC_XFORM_BOX                   1320
#define IDC_SCRATCH_EDIT_BOX            1321
#define IDC_SPOOL_EDIT_BOX              1322
#define IDC_ARCHIVE_BOX                 1323
#define IDC_HOTFOLDER_BOX               1324
#define IDC_AVAIL_BOX                   1325
#define IDC_NEW_BOX                     1326
#define IDC_BROWSE_PRMPT                1327
#define IDC_ELAPSED_TIME_HOLD           1328
#define IDC_ELAPSED_TIME_PRINT          1329
#define IDC_COLOR_TRANS_TYPE_PRMPT      1330
#define IDC_HOSTID_PRMPT                1331
#define ID_PRINT                        1332
#define IDC_EDIT_MEDIA                  1332
#define ID_RESCAN                       1333
#define IDC_IMAGE_REND_LABEL            1333
#define IDC_IMAGE_REND_INTENT_PRMPT     1333
#define ID_REDISPLAY_ONLY               1334
#define IDC_TEXT_REND_LABEL             1334
#define IDC_TEXT_REND_INTENT_PRMPT      1334
#define IDC_CROPPED_IMAGE_PANE          1335
#define IDC_RESET_HOT_FOLDER            1335
#define IDC_REND_INTENT_PRMPT           1340
#define IDC_PRINT                       1341
#define IDC_WIDTH_PROMPT                1342
#define IDC_HEIGHT_PROMPT               1343
#define IDC_LEFTLOGO_PRMPT              1344
#define IDC_RIGHTLOGO_PRMPT             1345
#define IDC_IP                          1346
#define IDC_INDEX_FILENAME              1347
#define IDC_BITMAPSAMPLING_PRMPT        1348
#define IDC_MAXIMAGES_PRMPT             1349
#define IDC_MAXIMAGES_EDIT              1350
#define IDC_MAXIMAGES_SPIN              1351
#define IDC_DISPLAY_IMAGENAME           1352
#define IDC_IMAGESIZE_WIDTH             1353
#define IDC_IMAGE_WIDTH_EDIT            1354
#define IDC_IMAGECOUNT                  1355
#define IDC_IMAGESIZE                   1356
#define IDC_IMAGE_WIDTH_SPIN            1357
#define IDC_IMAGESIZE_HEIGHT            1358
#define IDC_IMAGE_HEIGHT_EDIT           1359
#define IDC_IMAGE_HEIGHT_SPIN           1360
#define IDC_IMAGESIZE_CROP              1361
#define IDC_IMAGESIZE_FIT               1362
#define IDC_IMAGESIZE_UNITS_TEXT        1363
#define IDC_SELECT_PANE                 1364
#define IDC_WHITE_SPACE_UNITS_TEXT      1365
#define IDC_IMAGE_WIDTH_EDIT2           1366
#define IDC_IMAGE_WIDTH_SPIN2           1367
#define IDC_HORIZONTAL_WHITE_EDIT       1368
#define IDC_HORIZONTAL_WHITE_SPIN       1369
#define IDC_VERTICAL_WHITE_EDIT         1370
#define IDC_VERTICAL_WHITE_SPIN         1371
#define IDC_INDEX_COPIES                1373
#define IDC_INDEX_COPIES_SPIN           1374
#define IDC_CREATE_INDEX_TEXT           1375
#define IDC_ICC_PROFILE_MESSAGE         1376
#define IDC_HOTFOLDER_DELAY_TEXT        1377
#define IDC_PRODUCT_NAME                1378
#define IDC_PHZSERVER_GROUP             1379
#define IDC_HF_SELECTDPI_TEXT           1380
#define IDC_HF_VARIANCE_TEXT            1381
#define IDC_HF_INCHES_TEXT              1382
#define NEWMULTIOPEN                    1537
#define IDD_ADDFILES                    1537
#define IDD_VISUAL_XFORM1               1538
#define IDD_DIALOG_PREFS_COLOR1         1538
#define IDD_DIALOG_GPREFS_DEVLIST       1539
#define IDD_DIALOG_GPREFS_GENERAL       1540
#define IDD_DEVICE1                     1541
#define IDD_DIALOG_GPREFS_SERVER        1542
#define IDD_VISUAL_XFORM3               1543
#define IDD_TRANSFORM1                  1544
#define IDD_VISUAL_XFORM4               1544
#define IDD_DIALOG_GPREFS_TRANSFORM     1545
#define IDD_ADVANCED_DEVICE             1547
#define CG_IDD_PSOUT                    1548
#define CG_IDD_QUEUESTATUS2             1549
#define IDD_VISUAL_XFORM5               1550
#define CG_IDD_RIPSTATUS                1551
#define IDD_DIALOG_GPREFS_PRINTINDEX_old 1552
#define IDD_LICENSEMANAGER              1553
#define IDC_ACTIVATE                    1610
#define IDC_REMOVE                      1611
#define IDC_NOINTERNET                  1612
#define IDC_ACTIVATIONCODE_PRMPT        1613
#define IDC_WORKFORCESTATUS_PRMPT       1615
#define IDC_MID_PRMPT                   1616
#define IDC_SITECODE_PRMPT              1617
#define IDC_DAYSLEFT_PRMPT              1618
#define IDC_CDPRODUCER_PRMPT            1619
#define IDR_MAINFRAME3                  26567
#define IDR_MAINFRAME_1025              26568
#define IDR_MAINFRAME_1026              26569
#define IDB_SPLASHWND1                  26569
#define IDC_RESCAN                      30000
#define IDS_DEVICE_PPDDIR               32769
#define IDS_RP95_CBOARD_FMT             32770
#define ID_PREFERENCES_RIP              32771
#define IDS_RP95_REGISTRY_BASE          32771
#define ID_PREFERENCES_PREVIEW          32772
#define IDS_UNINSTALLER_KEY             32772
#define ID_PREFERENCES                  32773
#define ID_TOOLS_VERIFYQUEUE            32774
#define IDS_SYN_ERRMSG_FILEWASDELETED   32774
#define IDS_UNINSTALL                   32775
#define ID_VISUAL_XFORM                 32776
#define IDS_REMOVEDEVICES_APP           32776
#define IDS_OLDUNINSTALLER              32777
#define IDS_FILE_PROPERTIES             32778
#define ID_EDIT_DELETE                  32779
#define ID_EDIT_ADDFILES                32780
#define IDS_START_SERVER                32781
#define ID_EDIT_SELECTALL               32782
#define ID_FILE_PRINT_SEL               32783
#define ID_FILE_PRINT_PREVIEW_SEL       32784
#define ID_PROCESS_CANCELIMAGING        32785
#define ID_PROCESS_SKIPTONEXTFILE       32786
#define ID_PROCESS_PAUSEIMAGING         32787
#define ID_PREFERENCES_LOCAL            32788
#define ID_PREFERENCES_GLOBAL           32789
#define ID_PROCESS_RESUMEIMAGING        32790
#define ID_TEST_DOPRINTERSETUP          32791
#define IDS_NO_FONTS                    32792
#define IDS_SYN_ERRMSG_NODEFAULTPROFILE 32793
#define ID_VIEW_SERVERVIEW              32794
#define IDS_SYN_ERRMSG_INVALIDPROFILE   32794
#define ID_EDIT_ADDBATCHHEADER          32795
#define ID_EDIT_WINSPLITFILE            32796
#define ID_WINDOW_CLOSEALLPREVIEWS      32797
#define ID_TOOLS_TEST                   32798
#define ID_TOOLS_DELTEST                32799
#define ID_PREFERENCES_QUEUE            32800
#define ID_FILE_EXPLORER                32801
#define IDS_DONGLENT_REBOOT             32801
#define ID_TOOLS_EXPLORER               32802
#define ID_TOOLS_REPORT                 32804
#define ID_TOOLS_REPORT_PRINT_PREVIEW   32805
#define ID_TOOLS_REPORT_PRINT           32806
#define ID_OUR_FILE_PRINT               32807
#define ID_OUR_FILE_PRINT_SEL           32808
#define ID_OUR_FILE_PRINT_PREVIEW       32809
#define ID_WINDOW_CLOSE_ALL_PREVIEW     32810
#define ID_EDIT_COPYATTS                32811
#define ID_EDIT_PASTEATTS               32812
#define ID_APP_TESTPROCESS              32813
#define IDS_CUSTOMPAGE_UNITS            32813
#define ID_EDIT_RESETSTATUS             32837
#define ID_TOOLS_RESTART                32838
#define ID_TOOLS_SHCHANGENOTIFY         32839
#define ID_WEB                          32841
#define ID_TOOLS_SCSI_EXPLORER          32842
#define ID_REG                          32843
#define ID_TESTWIN_OPEN                 32844
#define ID_TESTWIN_CLOSE                32845
#define ID_FILE_NEW2                    32868
#define ID_TOOLS_LOG                    32871
#define ID_WEB_UPDATE                   32872
#define ID_TOOLS_PRINTLOG               32873
#define ID_TOOLS_RESETLOG               32874
#define ID_TOOLS_ARCHIVELOG             32875
#define ID_EDIT_RESETPROPS              32876
#define ID_TOOLS_SAVESTATE              32877
#define IDS_READY                       32877
#define ID_FILE_REINSTALLPRINTER        32878
#define ID_FILE_APPDRIVER_CONFIG        32879
#define ID_TOOLS_DONGLE_READER          32880
#define IDS_TRUEGRAPHX                  32880
#define ID_EDIT_JOBDESCRIPTION          32881
#define ID_TOOLS_SCANJOB                32882
#define IDS_LASTWINDOWPOSX              32882
#define ID_TOOLS_SELECTSCANNER          32883
#define IDS_LASTWINDOWPOSY              32883
#define IDS_EDIT_MEDIA                  32884
#define ID_OUR_FILE_PRINT_PREVIEW_HD    32888
#define ID_FILE_PRINT_PREVIEW_SEL_HD    32889
#define ID_OUR_FILE_PRINT_INDEX         32890
#define ID_OUR_FILE_PRINT_SEL_INDEX     32891
#define ID_TOOLS_LICENSE_MANAGER        32894
#define ID_HELP_REMOTE_DIAGNOSTIC       32895
#define ID_HELP_NEWINTHISVERSION        32896
#define ID_HELP_DESK                    32897
#define IDS_RASTERPLUS                  32998
#define IDS_RASTERPLUS_LITE             32999
#define IDS_PHZ_PRINTSERVER             32999
#define IDS_MAINFRAME_PHZ               33001
#define IDS_PHZ_PRINTSERVER_VER         33002
#define IDS_NEWVERSIONAVAIL             33003
#define IDS_NONEWVERSION                33004
#define IDS_DEVNOTFOUND                 57343
#define AFX_IDS_HELPMODEMESSAGE2        57347
#define IDS_DEVNOTFOUND_QUEUE           57347
#define AFX_IDS_IDLEMESSAGE2            57348
#define IDS_NOPASTE_DELETED             57348
#define IDS_INKJETPLUS                  57349
#define IDS_RIP_DLL                     57610
#define IDS_SNAP                        57611
#define IDS_EXCEED_WIDTH                57612
#define IDS_USERULERS                   57613
#define IDS_RULERSUNITS                 57614
#define IDS_DEVICE_DEVINSTALLDIR_MAC    57682
#define IDS_FFORMAT_PDF                 58000
#define IDS_FFORMAT_EXIF                58001
#define IDS_FFORMAT_SGI                 58002
#define IDS_DEVICE_PRINTERCAPS_FOLDER   58003
#define IDS_DEVICE_INKJET_REALNAME      58004
#define IDS_PREVCTRL_TTIP_NEXT          58050
#define IDS_PREVCTRL_TTIP_PREV          58051
#define IDS_PREVCTRL_TTIP_BEGIN         58052
#define IDS_PREVCTRL_TTIP_END           58053
#define IDS_PREVCTRL_TTIP_CLOSE         58054
#define IDS_PREVCTRL_TTIP_PRINT         58055
#define IDS_PREVCTRL_TTIP_ZOOMIN        58056
#define IDS_PREVCTRL_TTIP_ZOOMOUT       58057
#define IDS_COLOR_RED                   59142
#define IDS_COLOR_GREEN                 59143
#define IDS_COLOR_BLUE                  59144
#define IDS_COLOR_CYAN                  59145
#define IDS_COLOR_MAGENTA               59146
#define IDS_COLOR_YELLOW                59147
#define IDS_COLOR_BLACK                 59148
#define IDS_COLOR_L                     59149
#define IDS_COLOR_A                     59150
#define IDS_COLOR_B                     59151
#define IDS_COLOR_X                     59152
#define IDS_COLOR_Y                     59153
#define IDS_COLOR_Z                     59154
#define IDS_CTYPE_NONE                  59155
#define IDS_CTYPE_BASIC                 59156
#define IDS_CTYPE_ICC                   59157
#define IDS_PROFILEDIR                  59158
#define IDS_CORRECTIONTYPE              59159
#define CG_ID_VIEW_QUEUESTATUS          0xE804
#define CG_ID_VIEW_QUEUESTATUS2         0xE805
#define CG_ID_VIEW_PSOUT                0xE806
#define IDS_QUEUESTATUS_IDLE            59400
#define IDS_QUEUESTATUS_PRINT_SELECT    59401
#define IDS_QUEUESTATUS_PRINT_ALL       59402
#define IDS_QUEUESTATUS_PREVIEW_SELECT  59403
#define IDS_QUEUESTATUS_PREVIEW_ALL     59404
#define IDS_QUEUESTATUS_SERVER_WAITING  59405
#define IDS_QUEUESTATUS_PAUSED          59506
#define IDS_DONGLESECTION               59507
#define IDS_NT_DRIVERINSTALLED          59508
#define IDS_SELECT_SPOOL_DIR            59509
#define IDS_SCRATCHDISK                 59510
#define IDS_LOGFILE                     59511
#define IDS_CANTFINDDEVICE              59512
#define IDS_CANFINDDEVICE               59513
#define IDS_CHECKCLOSEQUEUE             59514
#define IDS_SELECT_SCRATCH_DIR          59515
#define IDS_HOTFOLDER                   59516
#define IDS_SELECT_HOTFOLDER_DIR        59517
#define IDS_PREVIEW_VT_SIZE             59518
#define IDS_OPENEXISTING_QUEUE          59518
#define IDS_RESETLOG                    59519
#define IDS_LOG_ARCHIVE_OK              59520
#define IDS_LOG_ARCHIVE_ERROR           59521
#define IDS_ARCHIVELOG_DLGPRMPT         59522
#define IDS_TRANSFORM_LASTWINDOWPOSY    59523
#define IDS_TRANSFORM_LASTWINDOWPOSX    59524
#define IDS_LAST_OPTION_TAB             59525
#define IDS_RPLOG_TITLE                 59526
#define IDS_APPLYDEFAULTS               59527
#define IDS_NOKEY_RETRY                 59528
#define IDS_ALWAYS_OPEN                 59529
#define IDS_AUTOADVANCE                 59530
#define IDS_LARGETOOLBAR                59531
#define IDS_DEFAULT_PROFILE             59532
#define IDS_DEFAULT_PROFILE_SUPPORT     59533
#define IDS_PI_SINGLEPAGE               59534
#define IDS_PI_IMAGENAME                59535
#define IDS_PI_IMAGEPERPAGE             59536
#define IDS_PI_IMAGECOUNT               59537
#define IDS_PI_IMAGESIZE                59538
#define IDS_PI_IMAGEHEIGHT              59539
#define IDS_PI_IMAGEWIDTH               59540
#define IDS_PI_IMAGETRANSFORM           59541
#define IDS_PI_IMAGEUNITS               59542
#define IDS_MISSING_CHANGE_LOG          59543
#define IDS_FFORMAT_FPX                 59999
#define IDS_DELETED_ADDENDUM            60000
#define IDS_FFORMAT_POSTSCRIPT          60001
#define IDS_FFORMAT_BATCHHEADER         60002
#define IDS_FFORMAT_PCX                 60003
#define IDS_FFORMAT_GIF                 60004
#define IDS_FFORMAT_TIFF                60005
#define IDS_FFORMAT_TARGA               60006
#define IDS_FFORMAT_BMP                 60007
#define IDS_FFORMAT_JFIF                60008
#define IDS_FFORMAT_JTIF                60009
#define IDS_FFORMAT_OS2                 60010
#define IDS_FFORMAT_CALS                60011
#define IDS_FFORMAT_MACPAINT            60012
#define IDS_FFORMAT_IMG                 60013
#define IDS_FFORMAT_MSP                 60014
#define IDS_FFORMAT_WPG                 60015
#define IDS_FFORMAT_RAS                 60016
#define IDS_FFORMAT_PCT                 60017
#define IDS_FFORMAT_PCD                 60018
#define IDS_FFORMAT_PNG                 60019
#define IDS_FFORMAT_UNKNOWN             60020
#define IDS_DISABLE_ENABLED_QUEUE       60021
#define IDS_DISABLE_ACTIVE_QUEUE        60022
#define IDS_PROPERTIES_FORMAT           60023
#define IDS_LASTTAB_PROFILE             60024
#define IDS_TEST                        60025
#define IDS_FFORMAT_PSD                 60025
#define IDS_DEVICE_DEVINSTALLDIR_2000   60026
#define IDS_DEVICE_DEPENDENT_FILESET_2000 60027
#define IDS_FFORMAT_UNSUPPORTED         60028
#define IDS_SYN_ERRMSG_UNSUPPORTEDFORMAT 60029
#define IDS_DEVICE_DEVINSTALLDIR        60030
#define IDS_DEVICE_DEVINSTALLDIR_ROOT   60031
#define IDS_DEVICE_DEVINSTALLDIR_2003   60031
#define IDS_DEVICE_DEPENDENT_FILESET_2003 60032
#define IDS_NOLOAD_ASPI                 60099
#define IDS_CBOX_ADVANCED_AUTOMATIC     60100
#define IDS_CBOX_ADVANCED_CUSTOM        60101
#define IDS_CBOX_ADVANCED_NONE          60102
#define IDS_CBOX_ADVANCED_BOX           60103
#define IDS_CBOX_BATCH_BLACK            60104
#define IDS_CBOX_BATCH_WHITE            60105
#define IDS_CBOX_BATCH_NONE             60106
#define IDS_CBOX_PREVIEW_SMALL          60107
#define IDS_CBOX_PREVIEW_MEDIUM         60108
#define IDS_CBOX_PREVIEW_LARGE          60109
#define IDS_CBOX_SERVER_DISABLED        60110
#define IDS_CBOX_SERVER_ENABLED         60111
#define IDS_CBOX_SERVER_ACTIVE          60112
#define IDS_CBOX_DEVSETUP_LANDSCAPE     60113
#define IDS_CBOX_DEVSETUP_PORTRAIT      60114
#define IDS_MRU_INSTALL_NT_DEF          60115
#define IDS_MEDIA_CHANGE_REINSTALL      60115
#define IDS_REINSTALL_PROMPT            60116
#define IDS_DEVICE_DEVINSTALLDIR_VISTA  60117
#define IDS_DEVICE_DEVINSTALLDIR_2008   60118
#define IDS_DEVICE_DEVINSTALLDIR_VISTA_AMD64 60119
#define IDS_DEVICE_DEPENDENT_FILESET_AMD64 60120
#define IDS_DEVICE_DEVINSTALLDIR_WINDOWS7 60121
#define IDS_DEVICE_DEVINSTALLDIR_WINDOWS7x64 60122
#define IDS_DEVICE_DEPENDENT_FILESET_W7X64 60123
#define IDS_DEVICE_DEVINSTALLDIR_WINDOWS8 60124
#define IDS_DEVICE_DEPENDENT_FILESET_WINDOWS8 60125
#define IDS_PROCESSING_FMT              61000
#define IDS_GLOBALPROPS_TITLE           61001
#define IDS_QUEUEPROPS_TITLE            61002
#define IDS_DEVICE_DEVINSTALLDIR_98     61003
#define IDS_DEVICE_DEVINSTALLDIR_ME     61004
#define IDS_DEVICE_DEVINSTALLDIR_XP     61005
#define IDS_PI_WHITE_SPACE              61006
#define IDS_PI_HORIZONTAL_WHITE         61007
#define IDS_PI_VERTICAL_WHITE           61008
#define IDS_PI_WHITESPACEUNITS          61009
#define IDS_PI_COPIES                   61010
#define IDS_PI_PANE                     61011
#define IDS_PI_MEDIA_SIZE               61012
#define IDS_OWNER_COLTITLE              61100
#define IDS_SIZE_COLTITLE               61101
#define IDS_SUBMITTED_COLTITLE          61102
#define IDS_STATUS_COLTITLE             61103
#define IDS_FILEOPENPREVIEW             61116
#define IDS_DEVINSTALL_ERR_NOLOADDEV    61204
#define IDS_DEVINSTALL_ERR_NOMAKESPD    61205
#define IDS_DEVINSTALL_ERR_BADCOPY      61206
#define IDS_TWAIN_ACQUIRE_ERROR         61207
#define IDS_SYN_ERRMSG_ALLOK            61216
#define IDS_SYN_ERRMSG_OUTOFMEMORY      61217
#define IDS_SYN_ERRMSG_OUTOFDISKSPACE   61218
#define IDS_SYN_ERRMSG_CANCELIMAGE      61219
#define IDS_SYN_ERRMSG_PRIVATEHALT      61220
#define IDS_ACCURATE_VIEW               61220
#define IDS_SYN_ERRMSG_PSERROR          61221
#define IDS_SYN_ERRMSG_FILENOTFOUND     61222
#define IDS_SYN_ERRMSG_STARTFAULT       61223
#define IDS_SYN_ERRMSG_NOPREVIEW        61223
#define IDS_SYN_ERRMSG_UNDEFINED        61224
#define IDS_SYN_ERRMSG_RIPNOTFOUND      61225
#define IDS_SYN_ERRMSG_RIPDLLNOTFOUND   61226
#define IDS_SYN_PSERR_DICT              61227
#define IDS_NO_OVERWRITE_DEFTRANSFORM   61227
#define IDS_SYN_PSERR_DICTOVER          61228
#define IDS_CANCELLING                  61228
#define IDS_SYN_PSERR_DICTUNDER         61229
#define IDS_RESET_HOT_FOLDER            61229
#define IDS_SYN_PSERR_EXECOVER          61230
#define IDS_SYN_ERRMSG_DEVINIT          61230
#define IDS_SYN_PSERR_HANDLE            61231
#define IDS_SYN_PSERR_INTERRUPT         61232
#define IDS_SYN_PSERR_ACCESS            61233
#define IDS_SYN_PSERR_EXIT              61234
#define IDS_SYN_PSERR_FILEACCESS        61235
#define IDS_SYN_PSERR_FONT              61236
#define IDS_SYN_PSERR_RESTORE           61237
#define IDS_SYN_PSERR_IOERROR           61238
#define IDS_SYN_PSERR_LIMIT             61239
#define IDS_SYN_PSERR_NOPOINT           61240
#define IDS_SYN_PSERR_RANGE             61241
#define IDS_SYN_PSERR_STACKOVER         61242
#define IDS_SYN_PSERR_STACKUNDER        61243
#define IDS_SYN_PSERR_SYNTAX            61244
#define IDS_SYN_PSERR_TIMEOUT           61245
#define IDS_SYN_PSERR_TYPE              61246
#define IDS_SYN_PSERR_UNDEFINED         61247
#define IDS_SYN_PSERR_UNDEFFILE         61248
#define IDS_SYN_PSERR_UNDEFRES          61249
#define IDS_SYN_PSERR_UNMATCHED         61250
#define IDS_SYN_PSERR_UNREG             61251
#define IDS_HOST_ADAPTER_ID             61251
#define IDS_SYN_PSSTAT_PROCESSING       61252
#define IDS_SYS_TIMER_ERROR             61253
#define PRIVATE_MSG_DOPREVIEW           61254
#define IDS_MEMAUTOCONFIG               61255
#define IDS_MEMSIZE_IMAGE               61256
#define IDS_MEMSIZE_PREVIEW             61257
#define IDS_GENERALSECTION              61258
#define IDS_TOOLBARSMALL                61259
#define IDS_ASSOCIATE_DONE              61259
#define IDS_DEF_PREF_TAB                61260
#define IDS_DEF_PREF_TAB_QPREFS         61260
#define IDS_DEVSECTION                  61261
#define IDS_DEF_PREF_TAB_GPREFS         61261
#define IDS_DEVDIR                      61262
#define IDS_PROGFILE_MISSING            61263
#define IDS_PHOTOGIZE                   61264
#define IDS_EXTSECTION                  61265
#define IDS_PRINTSERVER                 61265
#define IDS_EXT_POSTSCRIPT              61266
#define IDS_EXT_EPS                     61267
#define IDS_EXT_PCX                     61268
#define IDS_EXT_GIF                     61269
#define IDS_EXT_TIFF                    61270
#define IDS_EXT_TARGA                   61271
#define IDS_EXT_SCODL                   61272
#define IDS_TRANSFORM_DEFAULT           61273
#define IDS_TRANSSECTION                61274
#define IDS_TRANSFORMS                  61274
#define IDS_CUSTOMXFORMS                61274
#define DOCERR_NOTVALID                 61275
#define IDS_DEFAULT_DEVICE              61276
#define IDS_ENTRYAPP                    61277
#define IDS_PSCRIPTENGINE               61278
#define IDS_SYN_ERRMSG_NOROTATE_BMP     61278
#define IDS_FONTPATH                    61279
#define IDS_CANNOTLOADRIP               61280
#define IDS_NOKEY                       61281
#define IDS_DISPLAYDLL                  61282
#define IDS_USERINFO                    61283
#define IDS_ORGANIZATION                61284
#define IDS_USERNAME                    61285
#define IDS_WININI_DEVICES              61286
#define IDS_NOCLOSEAPP_WHILEACTIVE      61286
#define IDS_PRINTERPORTS                61287
#define IDS_CANCELIMAGING               61288
#define IDS_NOCLOSEQUEUE_WHILEACTIVE    61288
#define IDS_TRANSFORMCONFIG             61289
#define IDS_NULL_DEV_TRN                61290
#define IDS_XFORM_EXISTS                61291
#define IDS_XFORM_SETASCURRENT          61292
#define IDS_TEMPPATH                    61293
#define IDS_MULTIPLE_SELECTION_NAME     61294
#define IDS_RETAIN_ASPECT               61295
#define IDS_HATCH                       61296
#define IDS_SHOW_PREVIEW                61297
#define IDS_RIPERR_BADFORMAT            61298
#define IDS_PREVIEW_PAUSE               61298
#define IDS_WINSPLIT_SECTION            61299
#define IDS_WINSPLIT_DELETEFILE         61300
#define IDS_WINSPLIT_REMOVEFILE         61301
#define IDS_WINSPLIT_INSERTFILE         61302
#define IDS_ERRORSPLITTINGFILE          61303
#define IDS_PREVIEW_ICONIC              61304
#define IDS_PREVIEW_COMPRESSION         61305
#define IDS_QUEUE_FILTERIDX             61306
#define IDS_DEVICES                     61307
#define IDS_VISUALXF_REPAINT            61308
#define IDS_DEV_DLLNAME                 61309
#define IDS_DEVICE_DEFAULT              61310
#define IDS_PREVIEW_PROMPT              61311
#define IDS_PREVIEWDLL                  61312
#define IDS_PREVIEWDEV_NAME             61313
#define IDS_RIPERR_RIPTHRDBAD           61314
#define IDS_SYN_ERRMSG_RIPTHRDBAD       61314
#define IDS_DEV_DLLNAME_DEBUG           61315
#define IDS_PREVIEWDLL_DEBUG            61316
#define IDS_CHANGE_START_REPAINT        61317
#define IDS_SELECT_POLL_DIR             61318
#define IDS_ADDFILES_DLGPRMPT           61319
#define IDS_DEVICE_NFORMAT              61320
#define IDS_SERVER_VERSION              61321
#define IDS_ZEUS_CLIPFORMAT             61322
#define IDS_DEVICE_ENVIRONMENT_NT       61322
#define IDS_DEVICE_DEVENTRY             61323
#define IDS_DEVICE_COMMENT              61324
#define IDS_DEVICE_ENVIRONMENT          61325
#define IDS_DEVICE_LANG_MON             61326
#define IDS_DEVICE_LANG_MONITOR_DESC    61326
#define IDS_DEVICE_DATATYPE             61327
#define IDS_DEVICE_PSDRIVER             61328
#define IDS_DRIVER_OUR_PORT_MONITOR     61328
#define IDS_DEVICE_PSDRIVER_HLP         61329
#define IDS_DRIVER_OUR_LANG_MONITOR     61329
#define IDS_DEVICE_RENAME_INI           61330
#define IDS_DEVICE_RENAME_KEY           61331
#define IDS_SPD_DLLNAME                 61332
#define IDS_DEVICE_LAYOUT_DIR           61333
#define IDS_DEVICE_LAYOUT_FILE          61334
#define IDS_DEVICE_LAYOUT_SDN           61335
#define IDS_DEVICE_LAYOUT_SDF           61336
#define IDS_DEVICE_EXTRACTEXE           61337
#define IDS_DEVICE_INSTALL_LOCS_MRU     61338
#define IDS_DEVICE_PRINTPROCESSOR       61339
#define IDS_DEVICE_DEPENDENT_FILESET    61340
#define IDS_DEVICE_PSCRIPTSET1          61341
#define IDS_DEVICE_ENVIRONMENT_VISTA_AMD64 61341
#define IDS_CABINSTALL_PROMPT1          61342
#define IDS_CABINSTALL_PROMPT2          61343
#define IDS_ERROR_INSTALL_PRINTER       61344
#define IDS_DEVICE_INSTALL_LOCS_MRU_LIST 61345
#define IDS_DRIVER_HELP                 61346
#define IDS_DRIVER_DRIVER               61347
#define IDS_DRIVER_MONITOR              61348
#define IDS_DRIVER_LANGUAGE_MONITOR     61348
#define IDS_SELECT_INSTALL_DIR          61349
#define IDS_DEVICE_DELETEOK             61350
#define IDS_DRIVER_FONT                 61351
#define IDS_DRIVER_ICONLIB              61352
#define IDS_DEVICE_MONITORS             61353
#define IDS_DEVICE_LANG_MONITORS_DRIVER 61353
#define IDS_DEVICE_MONITORS_DRIVER      61354
#define IDS_DRIVER_PORT_MONITOR         61355
#define IDS_DEVICE_PORT_MONITORS_DRIVER 61356
#define IDS_DEVICE_INSTALLING           61357
#define IDS_DEVICE_DEVONPORT            61358
#define IDS_DEVICE_PORT                 61359
#define IDS_NTINSTALL_PROMPT1           61359
#define IDS_CHANGING_CONNECTION         61360
#define IDS_REPORT_EXT                  61361
#define IDS_CABINSTALL_PROMPT3          61361
#define IDS_REPORT_EXT2                 61362
#define IDS_DEV_DLLNAME_NT              61362
#define IDS_REPORT_BADFNAME             61363
#define IDS_DEV_DLLNAME_DEBUG_NT        61363
#define IDS_APPPATH                     61364
#define IDS_APPDIR                      61364
#define IDS_REPORT_VIEWER               61365
#define IDS_NTINSTALL_PROMPT3           61365
#define IDS_REPORT_NOVIEWER             61366
#define IDS_REPORT_NUMIMAGES            61367
#define IDS_REPORT_SUBTITLE             61367
#define IDS_REPORT_IMAGESTART           61368
#define IDS_REPORT_SESSION_START        61368
#define IDS_REPORT_SESSION_END          61369
#define IDS_REPORT_ENTRY                61370
#define IDS_QUEUE_CLOSE                 61370
#define IDS_REPORT_TITLE                61371
#define IDS_CONNECTION                  61372
#define IDS_REPORT_FONT                 61373
#define IDS_REPORT_DEVICE               61374
#define IDS_EXPAND_PIF                  61375
#define IDS_MRU_INSTALL_NT              61376
#define IDS_SERVER_TITLE                61377
#define IDS_RESET_SERVER_DEFAULTS       61377
#define IDS_CONNECTION_DEFAULT          61378
#define IDS_POLLDIR                     61379
#define IDS_CLONE                       61380
#define IDS_LOCKPROPERTIES              61381
#define IDS_OVERWRITE_TRANSFORM         61382
#define IDS_DEFAULTXFORMS               61383
#define IDS_CUSTOMXFORMNAME             61384
#define IDS_SMARTFIT                    61385
#define IDS_SMARTCROP                   61386
#define IDS_DELETEXFORM                 61387
#define IDS_IPCBASENAME                 61388
#define IDS_RIPPROCAPP_DEBUG            61389
#define IDS_RIPPROCAPP                  61390
#define IDS_NEWRIPSECTION               61391
#define IDS_NEWRIP_FONTPATH             61392
#define IDS_NEWRIP_TEMPPATH             61393
#define IDS_NEWRIP_LIBPATH              61394
#define IDS_NEWRIP_RESPATH              61395
#define IDS_NEWRIP_ATMPATH              61396
#define IDS_SPD_DLLNAME_NT              61396
#define IDS_NEWRIP_TTPATH               61397
#define IDS_DEVICE_DEPENDENT_FILESET_NT 61397
#define IDS_NEWRIP_PFORMAT              61398
#define IDS_NEEDTOREBOOT                61399
#define IDS_NEWRIP_PSOUT                61400
#define IDS_SERVER_ACTIVE               61400
#define IDS_EXTRACT_PIF                 61401
#define IDS_DRIVER_UI                   61402
#define IDS_CABFILE_INSTALL_START       61403
#define IDS_DEVICE_EXTRACTEXE_CHAIN     61404
#define IDS_VISUALXF_PSOUTTITLE         61405
#define IDS_POSTSCRIPT_OUTPUT           61406
#define IDS_SYN_ERRMSG_BADFORMAT        61407
#define IDS_STATUS_READING_FILE         61408
#define IDS_STATUS_SCANLINE             61409
#define IDS_DEVICE_DEVINSTALLDIR_NT     61410
#define IDS_STATUS_RENDERING            61411
#define IDS_STATUS_PRINTING_RED         61412
#define IDS_STATUS_PRINTING_GREEN       61413
#define IDS_STATUS_PRINTING_BLUE        61414
#define IDS_STATUS_PRINTING_CYAN        61415
#define IDS_STATUS_PRINTING_YELLOW      61416
#define IDS_STATUS_PRINTING_MAGENTA     61417
#define IDS_STATUS_PRINTING_BLACK       61418
#define IDS_STATUS_PRINTING_IMAGE       61419
#define IDS_STATUS_PRINTING_WHITE       61420
#define IDS_SERVER_DISABLED             61421
#define IDS_SERVER_ENABLED              61422
#define IDS_RESET_TO_DEFAULTS           61423
#define IDS_NO_LOAD_CONTROL_PANEL       61424
#define IDS_CONTROL_PRINTERS            61425
#define IDS_FILENAME_COLTITLE           61426
#define IDS_DESCRIPTION_COLTITLE        61427
#define IDS_LOCALPROPS_COLTITLE         61428
#define IDS_OLE_CBOARDHOLDER            61429
#define IDS_SAVE_PREVIEW_CHANGES        61430
#define IDS_BITMAP_DLL                  61431
#define IDS_DEFSERVER_XFORM             61432
#define IDS_PREVIEWEXPIRED              61433
#define IDS_EVALEXPIRED                 61433
#define IDS_ENABLE_POLLING              61434
#define IDS_IMAGE_ONLY_NEW              61435
#define IDS_DEFSERVER_DEVICE            61436
#define IDS_SERVER_DELAY                61437
#define IDS_DEFAULTPROFILE              61438
#define IDS_SERVER                      61439

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        525
#define _APS_NEXT_COMMAND_VALUE         32910
#define _APS_NEXT_CONTROL_VALUE         1381
#define _APS_NEXT_SYMED_VALUE           119
#endif
#endif
